// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	CLOUDFLARE_ACCOUNT: "e0cedd822a91d12ecc84a449230ce9cf";
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
